// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thvowhyaxvqdkcyzgkko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRodm93aHlheHZxZGtjeXpna2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzY5MjIsImV4cCI6MjA2NzgxMjkyMn0.3VM5lEAiW7fQBnkPjVYrMuKuEhJld8ceH8TeQINangQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});